address: https://test-stand.gb.ru/gateway/login
address_post: https://test-stand.gb.ru/api/posts
username: Sxcvb
password: 6c0cf2dc81
notMe_post_title: NEW POST
new_post_title: Арзамас
new_post_description: Нижегородская область
new_post_content: Арзамас, Нижегородская область